#  - Disables non-security update PRs
#  - Schedules security update PRs weekly
#  - Auto assigns PRs to the gnomad-browser team

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
    reviewers:
      - "broadinstitute/gnomad-browser"
