name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Use yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive --no-progress
      - name: Build packages
        run: yarn workspaces run build
      - name: Run ESLint on JavaScript files
        run: yarn run lint:js
      - name: Run ESLint on TypeScript files
        run: yarn run lint:ts
      - name: Run stylelint
        run: yarn run lint:css
      - name: Run tests
        run: yarn test
